arck8s: changes related to container insights extension specific things
NarayanThiru/azure-cli-extensions pull request #2
Opened 2020-09-09 22:40 UTC by ganga1980

---

arck8s: changes related to container insights extension specific things like create default workspace, add solution and get keys etc.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2020-09-10 13:57 UTC, NarayanThiru commented on src/k8s-extension/azext_k8s_extension/custom.py
> +        if not configuration_settings:
Since this will be common for all extension, these can be moved out; but let it be here, for now.  I'll move it when I fix the ConfigurationSettings and ConfigurationProtectedSettings.

2020-09-10 14:00 UTC, NarayanThiru commented on src/k8s-extension/azext_k8s_extension/containerinsights.py
> +# --------------------------------------------------------------------------------------------
I did only a light review of this file - not a thorough one.  As this is specific to ContainerInsights extension, I am trusting you to know what you are doing :)

2020-09-10 14:09 UTC, NarayanThiru requested changes
@ganga1980 , please address the comments

2020-09-10 14:09 UTC, NarayanThiru commented on src/k8s-extension/azext_k8s_extension/containerinsights.py
> +    while True:
Is it okay to have this infinite loop?  I suppose you are relying on ARM operation timeout.  Wanted to call out to ensure that is what you intend

2020-09-10 14:09 UTC, NarayanThiru commented on src/k8s-extension/azext_k8s_extension/containerinsights.py
> +        configuration_settings['omsagent.domain'] = 'opinsights.azure.us'
Add a blank line after the last line of the file

2020-09-10 21:57 UTC, ganga1980 commented on src/k8s-extension/azext_k8s_extension/custom.py
> +        if not configuration_settings:
> Since these checks for empty configuration_settings and configuration_protected_settings will be common for all extensions, these can be moved out; but let it be here, for now. I'll move it when I fix the ConfigurationSettings and ConfigurationProtectedSettings.

> Sure, but please make sure these objects are set to {} if there are not set. Since container insights code expects to these are valid objects and update the config settings.

2020-09-10 21:58 UTC, ganga1980 commented on src/k8s-extension/azext_k8s_extension/containerinsights.py
> +# --------------------------------------------------------------------------------------------
> I did only a light review of this file - not a thorough one. As this is specific to ContainerInsights extension, I am trusting you to know what you are doing :)

> Sure, :). This code owned by me and please direct to me or our team if you hear any customer issues  after the extension rolled out.

2020-09-10 21:59 UTC, ganga1980 commented on src/k8s-extension/azext_k8s_extension/containerinsights.py
> +    while True:
> Is it okay to have this infinite loop? I suppose you are relying on ARM operation timeout. Wanted to call out to ensure that is what you intend

> Yes, this same piece of the logic we have in azure cli for aks monitoring addon as well.

2020-09-11 02:00 UTC, ganga1980 commented on src/k8s-extension/azext_k8s_extension/containerinsights.py
> +        configuration_settings['omsagent.domain'] = 'opinsights.azure.us'
> Add a blank line after the last line of the file

Done.

2020-09-15 14:18 UTC, merged